screwdriver-cd/homepage

Rakefile
This doesn't exist in the container
=> Removing time (who needs time anyway)

Rakefile, _includes/css/agency.css, _includes/css/screwdriver.css, _includes/getstarted.html, _includes/header.html
- Adjusting tag-line of Screwdriver
- Fitting Darren's name into one line
- Link to Getting Started for Cluster Management
- Correcting weight to meet @petey's standards
- Fixing publishing by sourcing the file instead of executing
=> fix: 5 Fixes to various parts of the homepage

_config.yml, _includes/js.html
This is so we can get stats on impressions/visitors.
=> feat: Add Google Analytics

_includes/footer.html
I think it's the best place all contributors read at the first.
=> docs: Guide into contributing docs

README.md
As a result of a user observation, making some improvements to the README.
=> fix: Update README with links to documentation

_config.yml, _includes/team.html
Moving summer interns to the contributors list
=> fix: Move summer interns to contributors list

_includes/css/screwdriver.css, _includes/features.html, _includes/footer.html, _includes/getstarted.html, _includes/integrations.html, _includes/team.html, _layouts/default.html
Add features section and small changes to the footer.
Related to https://github.com/screwdriver-cd/screwdriver/issues/322
=> fix: Add features to homepage

_includes/features.html
This PR fixes a dead link and uses https.
=> fix: fix dead link and use https

Gemfile, Gemfile.lock, _includes/getstarted.html, screwdriver.yaml
**Issue #, if available:**
**Description of changes:**
I confirm that this contribution is made under the terms of your choice and that I have the authority necessary to make this contribution on behalf of its copyright owner.
=> fix: update link for sd in a box

README.md, _includes/footer.html
=> fix: Add Twitter

_config.yml
I updated my git user name. Syncing homepage with change.
=> fix: update git user name

_includes/head.html
CDF Incubating project. Add google analytics to site
Analytics for site
=> update head.html with GA for CDF

_includes/footer.html
Add a notice that this is an incubating project of the CDF
Add a notice and logo that this is an incubating project of the CDF
=> update footer with cdf logo

_includes/footer.html
Fixed some missing `<br>` and sized down logo
Fixed some missing `<br>` and sized down logo
=> updated logo

_includes/getstarted.html
docs: fix directory name
/data --> data/
update the docs
none
=> docs: fix directory name

_includes/css/screwdriver.css, _includes/events.html, _includes/events/cdcon.html, _includes/events/hacktoberfest.html, _includes/header.html, _layouts/default.html
=> update: add hacktoberfest and its css, also left hook for cdCon

js/agency.js
Add hash back to allow urls to be shared
=> fix: add hash link back

_includes/events/kubecon.html
Typo in event.
Fixes typo in event. 
=> Fix typo for Kubecon

_includes/header.html
=> fix: remove kubecon link

_includes/events.html
Update(remove) promotion for KubCon2020 
=> fix: update kubecon2020

_includes/events/cdcon.html
=> fix: update cdcon reference link

_includes/events/hacktoberfest.html
=> feat: add hacktoberfest

_includes/events/hacktoberfest.html
- make hacktoberfest image clickable
- 
=> fix: make hacktoberfest image clickable

_includes/events.html, _includes/header.html
=> fix: update hacktoberfest

_includes/events/hacktoberfest.html
API issue filter list to exclude UI issues
=> fix: update api issue list link
